config/routes.rb
Rails.application.routes.draw do

  root 'nearbybreweries#index'

  resources :breweries do
    resources :beers 
  end

  resources :beers do
      resources :reviews
    end

  get '/about' => 'main#about'
  get '/contact' => 'main#contact'
  get '/beerrun' => 'main#beerrun'

  get '/search' => 'nearbybreweries#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  has_many :review
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base

  has_many :beers
  has_many :features

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    full_address = [address, city, province, country].compact.join(', ')
  end 
  
end

app/models/nearbybrewery.rb
class Nearbybrewery < ActiveRecord::Base
 
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :beer
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def admin
    redirect_to '/login' unless current_user.admin == true 
  end



end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_action :find_beer, only: [:destroy, :update]
  before_action :find_brewery, only: [:destroy, :create, :new, :update]
  before_action :admin, only: [:new, :create, :edit, :update, :destroy]
 
 def new
  @beer = Beer.new
  @beer.brewery = @brewery
 end

 def create 
    @beer = Beer.new beer_params
    @beer.brewery = @brewery
    @beer.save
    redirect_to @brewery
 end 

 def destroy
    @beer.destroy
    redirect_to breweries_path
 end

 def edit
  end


  def update

    if @beer.update beer_params
      redirect_to @brewery
    else
      render :edit
    end
  end

 private 

  def find_brewery
    @brewery = Brewery.find params[:brewery_id]
  end

  def find_beer
    @beer = Beer.find params[:id]
  end

  def beer_params
    beer_params = params.require(:beer).permit(:name, :description, :style, :ibu, :abv, :color ) 
  end


end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :find_brewery, only: [:show, :edit, :update, :destroy]
  before_action :admin, only: [:new, :create, :edit, :update, :destroy]

 def new 
  @brewery = Brewery.new
   render :new 
 end 

 def create 
  @brewery = Brewery.new brewery_params
  @brewery.save
  redirect_to @brewery
 end 

 def show 
  @beer = Beer.new
  @beers = @brewery.beers
 end

 def index
  @brewery = Brewery.order(:id)
 end

 def destroy
    @brewery.destroy
    redirect_to breweries_path
 end

 def edit
  end


  def update

    if @brewery.update brewery_params
      redirect_to @brewery, notice: "Question Updated"
    else
      render :edit
    end
  end

 private 

  def full_address
    full_address = [address, city, province, country].compact.join(', ')
  end 

  def find_brewery
    @brewery = Brewery.find params[:id]
  end

  def brewery_params
    brewery_params = params.require(:brewery).permit(:name, :description, :address, :province, :city, :phone, :growler, :tour, :tasteing, :keg, :website, :instagram, :twitter, :facebook, :logo ) 
  end


  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/nearbybreweries_controller.rb
class NearbybreweriesController < ApplicationController 

    def index
      @search = params[:search] || current_city
      @address = Geocoder.coordinates(@search + ", Canada")
      @brewery = Brewery.near(
        [@address[0], @address[1]],
        20, units: :km)
      @hash = Gmaps4rails.build_markers(@brewery) do |brewery, marker|
        marker.lat brewery.latitude
        marker.lng brewery.longitude

        marker.infowindow "#{brewery.name}"

      end
    end

    private

    def current_city
      city = request.location.city
      if city.blank?
        "Vancouver"
      else
        city
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :find_review, only: [:destroy]
before_action :find_beer, only: [:destroy, :create]

before_action :authorize

def create
  @review = Review.new review_params
  @review.beer = @beer
  @review.user = current_user
  @review.save
  redirect_to @beer.brewery
end

private

  def find_beer
    @beer = Beer.find params[:beer_id]
  end

  def find_review
    @review = Review.find params[:id]
  end

  def review_params
    params.require(:review).permit(:body)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new 

  end

  def create 
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/nearbybreweries_helper.rb
module NearbybreweriesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/beers/_beer.html.erb
<div class="col-md-10 beerinfo">
  <div class="col-md-12 beerhead">
  <%=fa_icon "beer"%>
  <h4><%= beer.name %></h4>
  </div>

  <div class="description">
  <p><%= beer.description %></p>
  </div>

  <div class="beertypes col-md-12">
  <p>Style: <%= beer.style %></p>
  <p>IBU: <%= beer.ibu %></p>
  <p>ABV: <%= beer.abv %></p>
  </div>



<div class="showreview">
<h4>Reviews</h4>
<% beer.review.each do |review| %>
  <%= render partial: "/reviews/review", locals: {beer: beer, review: review} %>
<%end%>
</div>

<div class="col-md-12 reviewform">
 <%= render partial: "/reviews/form", locals: {beer: beer, review: @review} %>
</div>

</div>  

app/views/beers/_form.html.erb
<%= form_for [@brewery, @beer] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :style %>
  <%= f.text_field :style %>
  <br>
  <%= f.label :ibu %>
  <%= f.number_field :ibu %>
  <br>
  <%= f.label :abv %>
  <%= f.text_field :abv %>
  <br>
  <%= f.label :color %>
  <%= f.text_field :color %>
  <br>
  
  <%= f.submit %>

<% end %>

app/views/beers/edit.html.erb
<h2>Edit Beer</h2>

<%= link_to "Delete", brewery_beer_path, method: :delete, data: {confirm:"Are you sure?"}%>

<%= render "form" %>

app/views/beers/new.html.erb
<h2>New Beer</h2>

<%= render "form" %>

app/views/breweries/_form.html.erb
<%= form_for @brewery do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br>
  <%= f.label :province %>
  <%= f.text_field :province %>
 
  <br>
  <%= f.label :phone %>
  <%= f.telephone_field :phone %>
  <br>
  <%= f.label :website %>
  <%= f.text_field :website %>
  <br>
  <%= f.label :twitter %>
  <%= f.text_field :twitter %>
  <br>
  <%= f.label :instagram %>
  <%= f.text_field :instagram %>
  <br>
  <%= f.label :facebook %>
  <%= f.text_field :facebook %>
  <br>
  <%= f.label :growler %>
  <%= f.check_box :growler %>
  <br>
  <%= f.label :tour %>
  <%= f.check_box :tour%>
  <br>
  <%= f.label :tasteing %>
  <%= f.check_box :tasteing %>
  <br>
  <%= f.label :keg %>
  <%= f.check_box :keg %>
  <br>
  
  <%= f.submit %>
  
  <%end%>

app/views/breweries/edit.html.erb
<h2>Edit Brewery</h2>

<%= link_to "Delete", brewery_path, method: :delete, data: {confirm:"Are you sure?"}%>

<%= render "form" %>

app/views/breweries/index.html.erb
<div class="cards">
<% @brewery.each do |b| %>
  <div class="card">
    <div class="card-header">
      <%= link_to b.name, b %>
    </div>
    <div class="card-copy">
      <p><%= b.description %></p>
      <p><%=fa_icon "phone"%> <%= b.phone %></p>
      <a href="<%= b.website %>"><%= b.website %></a>
    </div>
    <div class="card-stats">
      <ul>
        <li>Growler <% if b.growler == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
        <li>Tour <% if b.tour == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
        <li>Tasteing <% if b.tasteing == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                      <% end %>
                    </li>
        <li>Keg <% if b.keg == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
      </ul>
    </div>
  </div>
<% end %>
</div>

app/views/breweries/new.html.erb
<h1> New Brewery </h1>

<%= render "form" %>

app/views/breweries/show.html.erb
<div class="brewery col-md 12">

<div class="col-md-8">

<div class="bhead col-md-12">

<h2><%= @brewery.name %></h2>
<div class="social">
  <a href="<%= @brewery.website %>"><%=fa_icon "wordpress"%></a>  
  <a href="<%= @brewery.facebook %>"><%=fa_icon "facebook"%></a>
  <a href="<%= @brewery.twitter %>"><%=fa_icon "twitter"%></a>
  <a href="<%= @brewery.instagram %>"><%=fa_icon "instagram"%></a>
</div>
</div>
  <h5><%= @brewery.description %></h5>
  <p> <%=fa_icon "phone"%><%= @brewery.phone %></p>
  
  <ul class="features">
        <li>Growler <% if @brewery.growler == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
        <li>Tour <% if @brewery.tour == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
        <li>Tasteing <% if @brewery.tasteing == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                      <% end %>
                    </li>
        <li>Keg <% if @brewery.keg == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
      </ul>
    </div>

  
  <div style='width: 300px;' class="bmap col-md-4">
    <div id="brewery_map" style='width: 100%; height: 270px;'></div>
  </div>

<div class="col-md-12">

  <h2> Beers </h2>


  <% @brewery.beers.each do |beer| %>
    <%= render partial: "/beers/beer", locals: {beer: beer} %>
  <% end %>
  
</div>
</div>
  <script>

   var mapStyle = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#D6D3C3"}]},
                  {"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#FFA836"},{"color":"#2AD194"}]},
                  {"featureType":"road","elementType":"geometry","stylers":[{"lightness":50},{"visibility":"simplified"}]},
                  {"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},
                  {"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":600}]},
                  {"featureType":"water","elementType":"all","stylers":[{"color":"#43BCCC"}]}]
  
    handler = Gmaps.build('Google');
    handler.buildMap({ 
      provider: {
          center:    new google.maps.LatLng(<%= @brewery.latitude%>, <%= @brewery.longitude%>),
          mapTypeId: google.maps.MapTypeId.ROADMAP,
          styles:    mapStyle
      }, 
      internal: {id: 'brewery_map'}}, function(){
        markers = handler.addMarkers([
        {
          "lat": <%= @brewery.latitude %>,
          "lng": <%= @brewery.longitude %>,
          "infowindow": "<%= @brewery.name %>"
        }
    ]);
    
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(18);

  });

  </script>

app/views/main/about.html.erb
  <div class="calltoaction wrapper">
    <h2>The Great Canadian Brewery Guide</h2>
    <p> Craft Beer in Canada is an ever growing industry with new breweries starting every year around the country. Great Canadian Breweries wants to curate all the cool Canadian breweries and make a list for all to use and enjoy good craft beer across the country. With information more than just the location and name, we want to be the only place people go on the web to find breweries across Canada. Letting consumers and coinsures know about new and old breweries and all they need to know before making the trek to the place where your favorite beer is made. Canadian craft beer is in its infancy and connecting Canada and the breweries together is our main goal.</p>
    <div class="line"></div>
  </div>
  

app/views/main/beerrun.html.erb
<div class="projects wrapper clearfix">
    <h2>Beer Run 2015</h2>
    <p>In the summer of 2015 Great Canadian Breweries will be driving across Canada, Starting from Tofino, BC and driving east to St Johns, NL (7,372 km), visiting all the great breweries along the way and documenting our travels and tours via video and blog entries. Hopefully this will help us gather great information and experience this great nation and all the great beer in it.</p>
    
    <div class="line"></div>
  </div>

app/views/main/blog.html.erb
<div class="blog wrapper clearfix">
    <h2>Blog</h2>
      <p>Check back soon for brewery reviews and more canadian beer infromation</p>

    <div class="line"></div>
  <div>

app/views/main/contact.html.erb
<div class="contact clearfix">
  <div class="wrapper">
    <h2>Contact</h2>
    <p>Did we miss something? A amazing brewery, Something cool to do on our beer run or just want to give a thanks. Send us a email.</p>
    <h5><a href="mailto:greatcanadianbreweries@gmail.com">GreatCanadianBreweries@gmail.com</a></h5>
    <ul>
      
    </ul>
  </div>
  </div>

app/views/nearbybreweries/index.html.erb
  
  <div class="search">
  <%= form_tag("/search", method: "get") do %>
  <span><%= text_field_tag :search, @search, class: "search-form" %></span>
  <% end %>
  </div>

<div id="map" style="height: 350px "></div>

<div class="cards">
<% @brewery.each do |b| %>
  <div class="card">
    <div class="card-header">
      <%= link_to b.name, b %>
    </div>
    <div class="card-copy">
      <p><%= b.description %></p>
      <p><%=fa_icon "phone"%> <%= b.phone %></p>
      <a href="<%= b.website %>"><%= b.website %></a>
    </div>
    <div class="card-stats">
      <ul>
        <li>Growler <% if b.growler == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
        <li>Tour <% if b.tour == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
        <li>Tasteing <% if b.tasteing == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                      <% end %>
                    </li>
        <li>Keg <% if b.keg == true %>
                      <%=fa_icon "check"%>
                    <% else %>
                      <%=fa_icon "times"%>
                    <% end %>
                    </li>
      </ul>
    </div>
  </div>
<% end %>
</div>





<script>

var mapStyle = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#D6D3C3"}]},
                  {"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#FFA836"},{"color":"#2AD194"}]},
                  {"featureType":"road","elementType":"geometry","stylers":[{"lightness":50},{"visibility":"simplified"}]},
                  {"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},
                  {"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":600}]},
                  {"featureType":"water","elementType":"all","stylers":[{"color":"#43BCCC"}]}]


  $(document).ready(function(){
    handler = Gmaps.build('Google');
    handler.buildMap({ 
      provider: {mapTypeId: google.maps.MapTypeId.ROADMAP,
          styles:    mapStyle}, 
      internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%= raw @hash.to_json %> );
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for [beer, (@review || Review.new)] do |f| %>
  <div class="form-group">
    <%= f.label "Review #{beer.name}" %>
    <%= f.text_area :body, class: "form-control" %>
    <%= f.submit'Submit', :class => 'btn btn-default'%>
  </div>
  <hr>
<%end%>

app/views/reviews/_review.html.erb
  

<div class="reviewuser"><h5><%= review.user.name %><h5></div>
<div class="well well-sm">
<p><%= review.body %></p>
</div>
<br>

app/views/session/new.html.erb
<h1>Login</h1>

<%= form_tag '/login' do %>

  Email: <%= text_field_tag :email %>
  Password: <%= password_field_tag :password %>
  <%= submit_tag "Submit" %>

<% end %>

<%= link_to 'Signup', '/signup' %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>