config/routes.rb
Rails.application.routes.draw do

  root 'nearbybreweries#index'

  resources :breweries do
    resources :beers 
  end

  resources :beers do
      resources :reviews
    end

  get '/about' => 'main#about'
  get '/contact' => 'main#contact'
  get '/beerrun' => 'main#beerrun'

  get '/search' => 'nearbybreweries#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  has_many :review
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base

  has_many :beers
  has_many :features

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    full_address = [address, city, province, country].compact.join(', ')
  end 
  
end

app/models/nearbybrewery.rb
class Nearbybrewery < ActiveRecord::Base
 
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :beer
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def admin
    redirect_to '/login' unless current_user.admin == true 
  end



end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_action :find_beer, only: [:destroy, :update]
  before_action :find_brewery, only: [:destroy, :create, :new, :update]
  before_action :admin, only: [:new, :create, :edit, :update, :destroy]
 
 def new
  @beer = Beer.new
  @beer.brewery = @brewery
 end

 def create 
    @beer = Beer.new beer_params
    @beer.brewery = @brewery
    @beer.save
    redirect_to @brewery
 end 

 def destroy
    @beer.destroy
    redirect_to breweries_path
 end

 def edit
  end


  def update

    if @beer.update beer_params
      redirect_to @brewery
    else
      render :edit
    end
  end

 private 

  def find_brewery
    @brewery = Brewery.find params[:brewery_id]
  end

  def find_beer
    @beer = Beer.find params[:id]
  end

  def beer_params
    beer_params = params.require(:beer).permit(:name, :description, :style, :ibu, :abv, :color ) 
  end


end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :find_brewery, only: [:show, :edit, :update, :destroy]
  before_action :admin, only: [:new, :create, :edit, :update, :destroy]

 def new 
  @brewery = Brewery.new
   render :new 
 end 

 def create 
  @brewery = Brewery.new brewery_params
  @brewery.save
  redirect_to @brewery
 end 

 def show 
  @beer = Beer.new
  @beers = @brewery.beers
 end

 def index
  @brewery = Brewery.order(:id)
 end

 def destroy
    @brewery.destroy
    redirect_to breweries_path
 end

 def edit
  end


  def update

    if @brewery.update brewery_params
      redirect_to @brewery, notice: "Question Updated"
    else
      render :edit
    end
  end

 private 

  def full_address
    full_address = [address, city, province, country].compact.join(', ')
  end 

  def find_brewery
    @brewery = Brewery.find params[:id]
  end

  def brewery_params
    brewery_params = params.require(:brewery).permit(:name, :description, :address, :province, :city, :phone, :growler, :tour, :tasteing, :keg, :website, :instagram, :twitter, :facebook, :logo ) 
  end


  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :find_review, only: [:destroy]
before_action :find_beer, only: [:destroy, :create]

before_action :authorize

def create
  @review = Review.new review_params
  @review.beer = @beer
  @review.user = current_user
  @review.save
  redirect_to @beer.brewery
end

private

  def find_beer
    @beer = Beer.find params[:beer_id]
  end

  def find_review
    @review = Review.find params[:id]
  end

  def review_params
    params.require(:review).permit(:body)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new 

  end

  def create 
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/nearbybreweries_helper.rb
module NearbybreweriesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_nav.html.erb
<header>
<nav class="navbar navbar-default">
 <div class="container-fluid">

<h1>Great Canadian Breweies</h1>
<div class='navbar-header'>
<a href="/" class="navbar-brand"><%= image_tag("logo.jpg") %></a>

<ul  class="nav navbar-nav">
  <li role="presentation"><%= link_to 'All Breweries', breweries_path, class: "navlink" %></li>
  <li role="presentation"><%= link_to 'Blog', "/", class: "disabled"%></li>
  <li role="presentation"><%= link_to 'Beer Run 2015', beerrun_path, class: "navlink" %></li>
  <li role="presentation"><%= link_to 'About', about_path, class: "navlink" %></li>
  <li role="presentation"><%= link_to 'Contact', contact_path, class: "navlink" %></li>
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><p class="navbar-text"><%=fa_icon "user"%><%= current_user.name %></p></li> <li><%= link_to "Logout", '/logout'%></li>
  <% else %>
    <li><%= link_to 'Login', '/login' %></li><li><%= link_to 'Signup', '/signup' %></li>
  <% end %>
</ul>    

</div>
</div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greatcanadianbreweries</title><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <meta charset="UTF-8">
  <meta name="keywords" content="Canadian, Breweries, Craft Beer, List, Beerrun, Beer ">
  <meta name="description" content="Great Canadian Breweries is the place to find all the best breweries across Canada. Striving for the biggest and most detailed list of all the breweries all over Canada. ">
  <meta name="author" content="Derek Barker">
</head>
<body>

<%= render partial: "/layouts/nav" %>

<div class="container">
<%= yield %>
</div>

</body>
</html>